Repository codesquad-masters2024-team09-step2/be-airdnb, pull requests merged in 2024-06, with the labels that each got.

#1 HTTP basic을 이용한 기본 회원가입 기능 구현
  .github/pull_request_template.md
  README.md
  src/main/java/com/airdnb/SecurityConfig.java
  src/main/java/com/airdnb/member/MemberController.java
  src/main/java/com/airdnb/member/MemberJapRepository.java
  src/main/java/com/airdnb/member/MemberMapper.java
  src/main/java/com/airdnb/member/MemberRepository.java
  src/main/java/com/airdnb/member/MemberService.java
  src/main/java/com/airdnb/member/dto/MemberRegistration.java
  src/main/java/com/airdnb/member/entity/Member.java
  src/test/java/com/airdnb/member/RegisterTest.java
Labels: enhancement

#3 Feature/item
  src/main/java/com/airdnb/global/BizException.java
  src/main/java/com/airdnb/global/NotFoundException.java
  src/main/java/com/airdnb/stay/StayController.java
  src/main/java/com/airdnb/stay/StayService.java
  src/main/java/com/airdnb/stay/entity/Stay.java
  src/main/java/com/airdnb/stay/repository/StayJpaRepository.java
  src/main/java/com/airdnb/stay/repository/StayRepository.java
Labels: enhancement

#5 Stay 코드 리팩토링 및 위도,경도 추가
  src/main/java/com/airdnb/global/status/Status.java
  src/main/java/com/airdnb/image/entity/Image.java
  src/main/java/com/airdnb/member/entity/Member.java
  src/main/java/com/airdnb/stay/StayService.java
  src/main/java/com/airdnb/stay/dto/StayCreateRequest.java
  src/main/java/com/airdnb/stay/dto/StayDetailQueryResponse.java
  src/main/java/com/airdnb/stay/entity/Location.java
  src/main/java/com/airdnb/stay/entity/Stay.java
  src/main/java/com/airdnb/stay/entity/StayComment.java
  src/main/java/com/airdnb/stay/repository/StayCommentJpaRepository.java
  src/main/java/com/airdnb/stay/repository/StayJpaRepository.java
Labels: enhancement

#6 jwt 파싱 로직 수정
  src/main/java/com/airdnb/security/JwtAuthenticationFilter.java
  src/main/java/com/airdnb/security/JwtUtil.java
Labels: enhancement

#7 Fix/context username
  README.md
  src/main/java/com/airdnb/member/MemberService.java
  src/main/java/com/airdnb/security/SecurityMember.java
Labels: bug, documentation, enhancement

#8 예약 기능 구현
  src/main/java/com/airdnb/global/ForbiddenException.java
  src/main/java/com/airdnb/member/entity/Member.java
  src/main/java/com/airdnb/reservation/InvalidReservationException.java
  src/main/java/com/airdnb/reservation/ReservationController.java
  src/main/java/com/airdnb/reservation/ReservationJpaRepository.java
  src/main/java/com/airdnb/reservation/ReservationRepository.java
  src/main/java/com/airdnb/reservation/ReservationService.java
  src/main/java/com/airdnb/reservation/dto/ReservationCreateRequest.java
  src/main/java/com/airdnb/reservation/dto/ReservationQueryResponse.java
  src/main/java/com/airdnb/reservation/entity/Reservation.java
  src/main/java/com/airdnb/reservation/entity/ReservationPeriod.java
  src/main/java/com/airdnb/stay/StayService.java
  src/main/java/com/airdnb/stay/dto/StayCreateRequest.java
  src/main/java/com/airdnb/stay/dto/StayDetailQueryResponse.java
  src/main/java/com/airdnb/stay/entity/Stay.java
Labels: enhancement

#9 member,security 이외의 패키지 리팩토링
  src/main/java/com/airdnb/global/ApiResponse.java
  src/main/java/com/airdnb/global/BizException.java
  src/main/java/com/airdnb/global/GlobalExceptionHandler.java
  src/main/java/com/airdnb/global/NotFoundException.java
  src/main/java/com/airdnb/global/UriMaker.java
  src/main/java/com/airdnb/global/exception/BizException.java
  src/main/java/com/airdnb/global/exception/ForbiddenException.java
  src/main/java/com/airdnb/global/exception/InvalidRequestException.java
  src/main/java/com/airdnb/global/exception/NotFoundException.java
  src/main/java/com/airdnb/image/ImageJpaRepository.java
  src/main/java/com/airdnb/image/ImageRepository.java
  src/main/java/com/airdnb/image/ImageService.java
  src/main/java/com/airdnb/image/entity/Image.java
  src/main/java/com/airdnb/image/entity/ImageStatus.java
  src/main/java/com/airdnb/member/MemberService.java
  src/main/java/com/airdnb/reservation/InvalidReservationException.java
  src/main/java/com/airdnb/reservation/ReservationController.java
  src/main/java/com/airdnb/reservation/ReservationJpaRepository.java
  src/main/java/com/airdnb/reservation/ReservationRepository.java
  src/main/java/com/airdnb/reservation/ReservationService.java
  src/main/java/com/airdnb/reservation/dto/ReservationCreate.java
  src/main/java/com/airdnb/reservation/dto/ReservationQueryResponse.java
  src/main/java/com/airdnb/reservation/entity/Reservation.java
  src/main/java/com/airdnb/reservation/entity/ReservationStatus.java
  src/main/java/com/airdnb/stay/StayController.java
  src/main/java/com/airdnb/stay/StayService.java
  src/main/java/com/airdnb/stay/dto/StayCommentDetail.java
  src/main/java/com/airdnb/stay/dto/StayCreate.java
  src/main/java/com/airdnb/stay/dto/StayDetailQueryResponse.java
  src/main/java/com/airdnb/stay/entity/CommentStatus.java
  src/main/java/com/airdnb/stay/entity/Stay.java
  src/main/java/com/airdnb/stay/entity/StayComment.java
  src/main/java/com/airdnb/stay/entity/StayStatus.java
  src/main/java/com/airdnb/stay/repository/StayCommentJpaRepository.java
  src/main/java/com/airdnb/stay/repository/StayCommentRepository.java
  src/main/java/com/airdnb/stay/repository/StayJpaRepository.java
  src/main/java/com/airdnb/stay/repository/StayRepository.java
  src/main/java/com/airdnb/staytag/StayTagJpaRepository.java
  src/main/java/com/airdnb/staytag/StayTagRepository.java
  src/main/java/com/airdnb/tag/TagJpaRepository.java
  src/main/java/com/airdnb/tag/TagRepository.java
  src/main/java/com/airdnb/tag/TagService.java
  src/main/java/com/airdnb/tag/dto/TagQueryResponse.java
Labels: enhancement

#10 jwt 로그아웃 기능 및 Member 패키지 리팩터링
  build.gradle
  src/main/java/com/airdnb/global/config/RedisConfig.java
  src/main/java/com/airdnb/global/constants/SecurityConstants.java
  src/main/java/com/airdnb/member/MemberController.java
  src/main/java/com/airdnb/member/MemberJpaRepository.java
  src/main/java/com/airdnb/member/MemberRepository.java
  src/main/java/com/airdnb/member/MemberService.java
  src/main/java/com/airdnb/security/LogoutService.java
  src/main/java/com/airdnb/security/SecurityConfig.java
  src/main/java/com/airdnb/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/airdnb/security/jwt/JwtBlacklistService.java
  src/main/java/com/airdnb/security/jwt/JwtUtil.java
Labels: enhancement

#11 jwt 생성시 로직 리팩토링
  src/main/java/com/airdnb/security/LogoutService.java
  src/main/java/com/airdnb/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/airdnb/security/jwt/JwtUtil.java
Labels: enhancement

#12 멤버 패키지의 서비스 dto 컨트롤러 dto 분리
  src/main/java/com/airdnb/member/MemberController.java
  src/main/java/com/airdnb/member/MemberMapper.java
  src/main/java/com/airdnb/member/dto/MemberRegistration.java
  src/main/java/com/airdnb/member/dto/MemberRegistrationRequest.java
  src/main/java/com/airdnb/member/dto/MemberVerification.java
  src/main/java/com/airdnb/member/dto/MemberVerificationRequest.java
Labels: enhancement

#13 숙소 필터링 기능 구현
  build.gradle
  src/main/java/com/airdnb/global/config/QueryDSLConfig.java
  src/main/java/com/airdnb/stay/StayController.java
  src/main/java/com/airdnb/stay/StayService.java
  src/main/java/com/airdnb/stay/dto/StayCreateRequest.java
  src/main/java/com/airdnb/stay/dto/StayListQueryResponse.java
  src/main/java/com/airdnb/stay/dto/StayPriceListQueryResponse.java
  src/main/java/com/airdnb/stay/dto/StayQueryCondition.java
  src/main/java/com/airdnb/stay/dto/StayQueryConditionRequest.java
  src/main/java/com/airdnb/stay/entity/Stay.java
  src/main/java/com/airdnb/stay/entity/StayType.java
  src/main/java/com/airdnb/stay/repository/StayCommentRepository.java
  src/main/java/com/airdnb/stay/repository/StayQueryRepository.java
  src/main/java/com/airdnb/stay/repository/StayQueryRepositoryImpl.java
  src/main/java/com/airdnb/stay/repository/StayRepository.java
Labels: enhancement

#14 호스트와 게스트간 채팅 서버 구현
  build.gradle
  src/main/java/com/airdnb/chat/ChatController.java
  src/main/java/com/airdnb/chat/ChatRoomController.java
  src/main/java/com/airdnb/chat/config/WebSocketConfig.java
  src/main/java/com/airdnb/chat/dto/ChatRoomCreation.java
  src/main/java/com/airdnb/chat/dto/ChatRoomCreationRequest.java
  src/main/java/com/airdnb/chat/dto/ChatRoomResponse.java
  src/main/java/com/airdnb/chat/dto/MessageCreation.java
  src/main/java/com/airdnb/chat/dto/MessageCreationRequest.java
  src/main/java/com/airdnb/chat/dto/MessageResponse.java
  src/main/java/com/airdnb/chat/entity/ChatMessage.java
  src/main/java/com/airdnb/chat/entity/ChatRoom.java
  src/main/java/com/airdnb/chat/entity/ChatStatus.java
  src/main/java/com/airdnb/chat/entity/MemberChatRoom.java
  src/main/java/com/airdnb/chat/entity/MessageType.java
  src/main/java/com/airdnb/chat/repository/ChatMessageRepository.java
  src/main/java/com/airdnb/chat/repository/ChatRoomRepository.java
  src/main/java/com/airdnb/chat/repository/MemberChatRoomRepository.java
  src/main/java/com/airdnb/chat/service/ChatRoomService.java
  src/main/java/com/airdnb/chat/service/ChatService.java
  src/main/java/com/airdnb/chat/service/MemberChatRoomService.java
  src/main/java/com/airdnb/global/config/WebConfig.java
  src/main/java/com/airdnb/member/MemberController.java
  src/main/java/com/airdnb/member/MemberService.java
  src/main/java/com/airdnb/member/dto/VerificationResponse.java
  src/main/java/com/airdnb/member/entity/Member.java
  src/main/java/com/airdnb/security/SecurityConfig.java
  src/main/java/com/airdnb/security/jwt/JwtAuthenticationFilter.java
Labels: enhancement

#15 채팅방 캐싱을 위한 스케줄링 어노테이션 및 성능테스트코드 추가
  src/main/java/com/airdnb/AirDnbApplication.java
  src/test/java/com/airdnb/chat/ChatServicePerformanceTest.java
Labels: enhancement

#17 채팅 도메인 리팩터링
  src/main/java/com/airdnb/chat/ChatController.java
  src/main/java/com/airdnb/chat/ChatRoomController.java
  src/main/java/com/airdnb/chat/dto/ChatRoomCreationRequest.java
  src/main/java/com/airdnb/chat/dto/ChatRoomRecipient.java
  src/main/java/com/airdnb/chat/dto/ChatRoomResponse.java
  src/main/java/com/airdnb/chat/dto/MessageCreation.java
  src/main/java/com/airdnb/chat/dto/MessageCreationRequest.java
  src/main/java/com/airdnb/chat/entity/ChatRoom.java
  src/main/java/com/airdnb/chat/service/ChatRoomCreation.java
  src/main/java/com/airdnb/chat/service/ChatRoomService.java
  src/main/java/com/airdnb/chat/service/ChatService.java
  src/main/java/com/airdnb/chat/service/MessageCreation.java
  src/main/java/com/airdnb/global/constants/ChatConstants.java
  src/test/java/com/airdnb/chat/ChatServicePerformanceTest.java
Labels: enhancement

#18 회원가입 id 및 로그인 중복처리
  src/main/java/com/airdnb/member/MemberRepository.java
  src/main/java/com/airdnb/member/MemberService.java
Labels: bug

#20 선착순 쿠폰 및 대기열 기능 구현
  src/main/java/com/airdnb/coupon/CouponController.java
  src/main/java/com/airdnb/coupon/CouponService.java
  src/main/java/com/airdnb/coupon/dto/CouponDetail.java
  src/main/java/com/airdnb/coupon/dto/CouponRequestResultDetail.java
  src/main/java/com/airdnb/coupon/entity/Coupon.java
  src/main/java/com/airdnb/coupon/entity/CouponRequestResult.java
  src/main/java/com/airdnb/coupon/entity/CouponStatus.java
  src/main/java/com/airdnb/coupon/repository/AppliedMemberRepository.java
  src/main/java/com/airdnb/coupon/repository/CouponCountRepository.java
  src/main/java/com/airdnb/coupon/repository/CouponQueueRepository.java
  src/main/java/com/airdnb/coupon/repository/CouponRepository.java
  src/main/java/com/airdnb/coupon/repository/CouponRequestResultRepository.java
  src/main/java/com/airdnb/security/SecurityMemberProvider.java
  src/main/java/com/airdnb/security/jwt/JwtAuthenticationFilter.java
  src/test/java/com/airdnb/coupon/CouponServiceTest.java
Labels: enhancement
